export const Art = () => {
  return (
    <div class="art">
      <div id="skills-container" class="hide">
        <canvas width="500" height="500" id="skills-canvas">
          <ul id="skills-cloud">
            <li>
              <a
                class="font-bigger2"
                href="https://en.wikipedia.org/wiki/React_(web_framework)"
                target="_blank"
                rel="noopener"
              >
                React
              </a>
            </li>
            <li>
              <a
                class="font-bigger2"
                href="https://en.wikipedia.org/wiki/Angular_(web_framework)"
                target="_blank"
                rel="noopener"
              >
                Angular
              </a>
            </li>
            <li>
              <a
                class="font-bigger3"
                href="https://en.wikipedia.org/wiki/Reactive_programming"
                target="_blank"
                rel="noopener"
              >
                RxJS
              </a>
            </li>
            <li>
              <a
                class="font-bigger3"
                href="https://en.wikipedia.org/wiki/TypeScript"
                target="_blank"
                rel="noopener"
              >
                TypeScript
              </a>
            </li>
            <li>
              <a
                class="font-bigger2"
                href="https://en.wikipedia.org/wiki/Sass_(stylesheet_language)"
                target="_blank"
                rel="noopener"
              >
                SASS
              </a>
            </li>
            <li>
              <a
                class="font-bigger3"
                href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language)"
                target="_blank"
                rel="noopener"
              >
                C#
              </a>
            </li>
            <li>
              <a
                class="font-bigger2"
                href="https://en.wikipedia.org/wiki/.NET_Framework"
                target="_blank"
                rel="noopener"
              >
                .NET
              </a>
            </li>

            <li>
              <a
                class="font-bigger1"
                href="https://en.wikipedia.org/wiki/Node.js"
                target="_blank"
                rel="noopener"
              >
                Node.js
              </a>
            </li>
            <li>
              <a
                class="font-bigger2"
                href="https://en.wikipedia.org/wiki/Git"
                target="_blank"
                rel="noopener"
              >
                Git
              </a>
            </li>
            <li>
              <a
                href="https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)"
                target="_blank"
                rel="noopener"
              >
                Bootstrap
              </a>
            </li>
            <li>
              <a
                class="font-bigger1"
                href="https://en.wikipedia.org/wiki/JQuery"
                target="_blank"
                rel="noopener"
              >
                jQuery
              </a>
            </li>
            <li>
              <a href="http://mongoosejs.com/" target="_blank" rel="noopener">
                MongoDB
              </a>
            </li>
            <li>
              <a
                class=""
                href="https://en.wikipedia.org/wiki/PostgreSQL"
                target="_blank"
                rel="noopener"
              >
                PostgreSQL
              </a>
            </li>
            <li>
              <a
                href="https://en.wikipedia.org/wiki/Database"
                target="_blank"
                rel="noopener"
              >
                SQL/NoSQL
              </a>
            </li>
            <li>
              <a
                href="https://en.wikipedia.org/wiki/React_Native"
                target="_blank"
                rel="noopener"
              >
                React Native
              </a>
            </li>
            <li>
              <a
                href="https://en.wikipedia.org/wiki/D3.js"
                target="_blank"
                rel="noopener"
              >
                D3.js
              </a>
            </li>
            <li>
              <a
                href="https://en.wikipedia.org/wiki/GraphQL"
                target="_blank"
                rel="noopener"
              >
                GraphQL
              </a>
            </li>
            <li>
              <a
                href="https://en.wikipedia.org/wiki/Express.js"
                target="_blank"
                rel="noopener"
              >
                Express.js
              </a>
            </li>
            <li>
              <a
                href="https://en.wikipedia.org/wiki/Amazon_Web_Services"
                target="_blank"
                rel="noopener"
              >
                AWS
              </a>
            </li>
          </ul>
        </canvas>
      </div>
    </div>
  )
}
